// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_the_magnet = "CgkIn6So1LATEAIQCg"; // <GPGSID>
        public const string achievement_newbie = "CgkIn6So1LATEAIQAg"; // <GPGSID>
        public const string achievement_babyface = "CgkIn6So1LATEAIQBw"; // <GPGSID>
        public const string achievement_the_king = "CgkIn6So1LATEAIQDA"; // <GPGSID>
        public const string achievement_the_arrow = "CgkIn6So1LATEAIQBQ"; // <GPGSID>
        public const string achievement_gentle_giant = "CgkIn6So1LATEAIQCQ"; // <GPGSID>
        public const string leaderboard_time_attack_leader = "CgkIn6So1LATEAIQAQ"; // <GPGSID>
        public const string achievement_the_artist = "CgkIn6So1LATEAIQBg"; // <GPGSID>
        public const string achievement_rookie = "CgkIn6So1LATEAIQAw"; // <GPGSID>
        public const string achievement_little_john = "CgkIn6So1LATEAIQCA"; // <GPGSID>
        public const string achievement_superman = "CgkIn6So1LATEAIQDQ"; // <GPGSID>
        public const string achievement_the_cowboy = "CgkIn6So1LATEAIQCw"; // <GPGSID>

}

